/*
 * Requirements page — tabbed PRD viewer.
 * Source: data/prd.json (regenerated by `node scripts/extract-prd.js`).
 * Tabs are extracted from the .docx Title style; content blocks are rendered
 * as h1/h2/h3/h4/p/ul. Activates a tab via ?tab=<slug>.
 */

import { renderChrome } from '../chrome.js';

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function renderBlock(b) {
  switch (b.type) {
    case 'h1': return `<h1>${escapeHtml(b.text)}</h1>`;
    case 'h2': return `<h2>${escapeHtml(b.text)}</h2>`;
    case 'h3': return `<h3>${escapeHtml(b.text)}</h3>`;
    case 'h4': return `<h4>${escapeHtml(b.text)}</h4>`;
    case 'p':  return `<p>${escapeHtml(b.text)}</p>`;
    case 'ul': return `<ul>${b.items.map(li => `<li>${escapeHtml(li)}</li>`).join('')}</ul>`;
    default: return '';
  }
}

function countSections(blocks) {
  return blocks.filter(b => b.type === 'h1' || b.type === 'h2').length;
}

// Tabs that exist in the source doc as bare section dividers (no real content)
// and would just confuse the rail. The substantive successor tab carries the
// actual material — e.g. "💫 Product Vision" is a divider, "Remedy Product
// Vision" is the real content.
const HIDE_TABS_BY_TITLE = new Set([
  '💫 Product Vision',
  '🛣️ Roadmap',
]);

let tabs = [];

function renderRail(activeSlug) {
  const rail = document.getElementById('prd-rail');
  rail.innerHTML = `
    <span class="prd-rail-label">Tabs · ${tabs.length}</span>
    ${tabs.map(t => `
      <button class="prd-tab ${t.slug === activeSlug ? 'active' : ''}" data-slug="${t.slug}">
        <span>${escapeHtml(t.title)}</span>
        <span class="prd-tab-count">${countSections(t.blocks)}</span>
      </button>
    `).join('')}
  `;
  rail.querySelectorAll('.prd-tab').forEach(btn => {
    btn.addEventListener('click', () => setActive(btn.dataset.slug));
  });
}

function renderContent(tab) {
  const el = document.getElementById('prd-content');
  if (!tab) {
    el.innerHTML = `<div class="empty-state">No tab selected.</div>`;
    return;
  }
  el.innerHTML = `
    <p class="prd-tab-meta">${countSections(tab.blocks)} section${countSections(tab.blocks) !== 1 ? 's' : ''} · ${tab.blocks.length} block${tab.blocks.length !== 1 ? 's' : ''}</p>
    <h1>${escapeHtml(tab.title)}</h1>
    ${tab.blocks.map(renderBlock).join('')}
  `;
  el.scrollTop = 0;
  window.scrollTo({ top: el.getBoundingClientRect().top + window.scrollY - 80, behavior: 'smooth' });
}

function setActive(slug) {
  const tab = tabs.find(t => t.slug === slug) || tabs[0];
  const url = new URL(window.location.href);
  url.searchParams.set('tab', tab.slug);
  window.history.replaceState({}, '', url);
  renderRail(tab.slug);
  renderContent(tab);
}

async function init() {
  renderChrome({ active: 'requirements' });
  try {
    const res = await fetch('./data/prd.json', { cache: 'no-store' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    tabs = (data.tabs || []).filter(t => !HIDE_TABS_BY_TITLE.has(t.title));
    if (!tabs.length) {
      document.getElementById('prd-content').innerHTML = `<div class="empty-state">PRD has no tabs.</div>`;
      return;
    }
    const params = new URLSearchParams(window.location.search);
    const initial = params.get('tab') || tabs[0].slug;
    setActive(initial);
  } catch (err) {
    document.getElementById('prd-content').innerHTML = `<div class="empty-state">Could not load PRD content (${escapeHtml(err.message)}). The live Google Doc is still available via the button above.</div>`;
  }
}

init();
